user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
}

http {

	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers on;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	gzip on;
	gzip_comp_level 5;
	gzip_min_length 256;
	gzip_vary on;
	gzip_proxied any;
	gzip_types
		text/plain text/css text/javascript application/javascript
		application/json application/x-javascript text/xml application/xml
		image/svg+xml font/woff2;

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}

stream {
	map $ssl_preread_server_name $backend_addr {
                setai.no                   127.0.0.1:8447;
                www.setai.no               127.0.0.1:8447;
                seo.setai.no                  127.0.0.1:8446;
                www.seo.setai.no              127.0.0.1:8446;
		shahnameh.setaei.com        127.0.0.1:8444;
		admin.shahnameh.setaei.com  127.0.0.1:8444;
		trustai.no                  127.0.0.1:8445;
		www.trustai.no              127.0.0.1:8445;
                lashinebeauty.com      127.0.0.1:8448;
                www.lashinebeauty.com  127.0.0.1:8448;
                somi.setai.no          127.0.0.1:8449;
		stapay.setai.no            127.0.0.1:8450;
		dadashi.no                 127.0.0.1:8451;
		www.dadashi.no             127.0.0.1:8451;
		3real.setaei.com           127.0.0.1:8452;
		somiklinikken.no           127.0.0.1:8453;
		www.somiklinikken.no       127.0.0.1:8453;
		default                     127.0.0.1:4443;
	}

	server {
		listen 443;
		ssl_preread on;
		proxy_pass $backend_addr;
		proxy_protocol on;
	}
}
